# Generated by Django 2.2.5 on 2019-10-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='paySystem',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='telegramBotToken',
        ),
        migrations.AddField(
            model_name='session',
            name='endDate',
            field=models.DateField(default=None, verbose_name='Дата окончания показа сеанса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startDate',
            field=models.DateField(verbose_name='Дата начала показа сеанса'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TelegramUser'),
        ),
        migrations.DeleteModel(
            name='PaySystem',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.StaffPosition'),
            preserve_default=False,
        ),
    ]
