# Generated by Django 2.2.5 on 2019-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191009_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
