# Generated by Django 2.2.5 on 2019-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_cinema_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Режиссер'),
        ),
    ]
