# Generated by Django 2.2.5 on 2019-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_movie_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.CharField(default='', max_length=255, verbose_name='Длительность'),
        ),
    ]
