# Generated by Django 2.2.5 on 2019-11-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20191109_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionmovieday',
            name='sessions',
        ),
        migrations.AddField(
            model_name='sessionmovieday',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Session'),
            preserve_default=False,
        ),
    ]
