# Generated by Django 2.2.5 on 2019-10-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_setting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysystem',
            name='paySystemToken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paySystemToken', to='bot.Token'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegramBotToken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegramBotToken', to='bot.Token'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
