# Generated by Django 2.2.5 on 2019-10-09 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20191009_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='registrationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='paysystem',
            name='paySystemToken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Token'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegramBotToken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Token'),
        ),
    ]
