# Generated by Django 2.2.5 on 2019-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, default='RU', max_length=5, null=True, verbose_name='Язык'),
        ),
    ]
