# Generated by Django 2.2.5 on 2019-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20191015_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='cashback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сумма кэшбэка'),
        ),
    ]
